# Generated by Django 5.1.4 on 2025-02-26 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stu_id', models.IntegerField()),
                ('Course_id', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Batch', models.CharField(max_length=50)),
                ('Duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=5)),
                ('stu_id', models.CharField(max_length=50)),
                ('course_id', models.CharField(max_length=50, null=True)),
                ('paid_date', models.DateField(auto_now_add=True)),
                ('total_paid', models.IntegerField(default=0)),
                ('current_paid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Mobile_no', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('Fees', models.IntegerField(null=True)),
                ('Total', models.IntegerField(default=0)),
                ('Selected_course', models.ForeignKey(default='Select One', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stu_details.courses')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stu_details.batch')),
                ('duration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stu_details.duration')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu_details.gender')),
            ],
        ),
    ]
