# Generated by Django 5.1.4 on 2025-03-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_details', '0003_expences_expence_amount_expences_expence_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expences',
            name='Total_Expences',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='expences',
            name='closing_balance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='expences',
            name='opening_balance',
            field=models.FloatField(null=True),
        ),
    ]
