# Generated by Django 5.1.4 on 2025-03-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_details', '0004_expences_total_expences_expences_closing_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='balance_amount',
            field=models.IntegerField(null=True),
        ),
    ]
